# Generated by Django 5.1.4 on 2024-12-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOM_ID', models.IntegerField()),
                ('product_ID', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('material_name', models.CharField(max_length=255)),
                ('material_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_ID', models.IntegerField()),
                ('material_name', models.CharField(max_length=255)),
                ('material_inventory', models.IntegerField()),
                ('material_safe_inventory', models.IntegerField()),
                ('material_inventory_status', models.CharField(choices=[('充足', '充足'), ('低於安全庫存', '低於安全庫存'), ('缺貨', '缺貨')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_prediction', models.IntegerField()),
                ('material_inventory', models.IntegerField()),
                ('material_safe_inventory', models.IntegerField()),
                ('restock_date', models.DateField()),
                ('restock_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ID', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_inventory', models.IntegerField()),
                ('product_safe_inventory', models.IntegerField()),
                ('product_inventory_status', models.CharField(choices=[('充足', '充足'), ('低於安全庫存', '低於安全庫存'), ('缺貨', '缺貨')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.IntegerField()),
                ('order_date', models.DateField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('material_name', models.CharField(max_length=255)),
                ('material_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_status', models.CharField(choices=[('處理中', '處理中'), ('已完成', '已完成'), ('已取消', '已取消')], max_length=50)),
                ('order_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_prediction', models.IntegerField()),
                ('product_inventory', models.IntegerField()),
                ('product_safe_inventory', models.IntegerField()),
                ('restock_date', models.DateField()),
                ('restock_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_ID', models.IntegerField()),
                ('task_date', models.DateField()),
                ('task_action', models.CharField(choices=[('生產', '生產'), ('發貨', '發貨'), ('訂購', '訂購')], max_length=50)),
                ('task_content', models.TextField()),
                ('task_status', models.CharField(choices=[('未完成', '未完成'), ('完成', '完成')], max_length=50)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.productionorder')),
            ],
        ),
    ]
