# Generated by Django 4.2 on 2025-01-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_product_product_price_alter_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_ID',
        ),
        migrations.AlterField(
            model_name='bom',
            name='material_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.material'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bom_product_id', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bom_product_name', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='materialrestock',
            name='material_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_material_inventory', to='operations.material'),
        ),
        migrations.AlterField(
            model_name='materialrestock',
            name='material_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_material_name', to='operations.material'),
        ),
        migrations.AlterField(
            model_name='materialrestock',
            name='material_safe_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_material_safe_inventory', to='operations.material'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='material_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_material_name', to='operations.material'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_product_name', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='productrestock',
            name='product_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_product_inventory', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='productrestock',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_product_name', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='productrestock',
            name='product_safe_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_product_safe_inventory', to='operations.product'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_order_id', to='operations.productionorder'),
        ),
    ]
