# Generated by Django 4.2 on 2025-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_bom_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='material_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
