# Generated by Django 4.2 on 2025-01-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_alter_productionorder_material_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
