# Generated by Django 5.1.4 on 2024-12-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('last_purchase_date', models.DateField()),
                ('avg_purchase_interval', models.IntegerField()),
                ('avg_purchase_value', models.FloatField()),
                ('lifetime_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketingMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=255)),
                ('seasonal_sales', models.FloatField()),
                ('seasonal_growth_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.IntegerField()),
                ('order_date', models.DateField()),
                ('order_product', models.CharField(max_length=255)),
                ('order_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('處理中', '處理中'), ('已完成', '已完成'), ('已取消', '已取消')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RFMAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('monetary', models.FloatField()),
                ('rfm_value', models.FloatField()),
                ('customer_group', models.CharField(choices=[('高價值顧客', '高價值顧客'), ('中價值顧客', '中價值顧客'), ('低價值顧客', '低價值顧客')], max_length=50)),
                ('most_valuable_customer', models.CharField(max_length=255)),
                ('marketing_strategy_suggestion', models.TextField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_ID', models.IntegerField()),
                ('task_date', models.DateField()),
                ('task_action', models.CharField(choices=[('發貨', '發貨'), ('退貨', '退貨')], max_length=50)),
                ('task_content', models.TextField()),
                ('task_status', models.CharField(choices=[('未完成', '未完成'), ('完成', '完成')], max_length=50)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customerorder')),
            ],
        ),
    ]
