# Generated by Django 4.2 on 2024-12-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_product_product_price_alter_product_product_id'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avg_customer_years',
            field=models.FloatField(default=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avg_purchase_interval',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avg_purchase_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_ID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lifetime_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.product'),
        ),
    ]
