# Generated by Django 4.2 on 2025-01-01 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_task_task_id_alter_bom_material_name_and_more'),
        ('crm', '0002_customer_avg_customer_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='required_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.product'),
        ),
    ]
