# Generated by Django 4.2 on 2025-01-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customerorder_required_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lifetime_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
