# Generated by Django 4.2 on 2025-01-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_customer_id_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfmanalysis',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.customer'),
        ),
    ]
