# Generated by Django 4.2 on 2025-01-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_rfmanalysis_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfmanalysis',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
