# Generated by Django 4.2 on 2025-01-02 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customer_id_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfmanalysis',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
