# Generated by Django 4.2 on 2025-01-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_rfmanalysis_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfmanalysis',
            name='recency',
        ),
    ]
