# Generated by Django 4.2 on 2025-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_rfmanalysis_recency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfmanalysis',
            name='recency',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='customer_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='frequency',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='marketing_strategy_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='monetary',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='most_valuable_customer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='rfm_value',
            field=models.FloatField(blank=True),
        ),
    ]
