# Generated by Django 4.2 on 2025-01-02 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_rfmanalysis_recency_alter_rfmanalysis_customer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfmanalysis',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='monetary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='recency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='rfm_value',
            field=models.FloatField(),
        ),
    ]
