# Generated by Django 4.2 on 2025-01-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_rfmanalysis_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfmanalysis',
            name='frequency',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='monetary',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='recency',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rfmanalysis',
            name='rfm_value',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
