# Generated by Django 4.2 on 2025-01-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_rfmanalysis_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avg_customer_years',
            field=models.FloatField(blank=True, default=3),
        ),
    ]
