# Generated by Django 4.2 on 2025-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_customer_avg_customer_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmetrics',
            name='quarter_growth_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
